apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-pipeline
  labels:
    app: feedback-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feedback-pipeline
  template:
    metadata:
      labels:
        app: feedback-pipeline
    spec:
      containers:
      - name: feedback-pipeline
        image: kartikjalgaonkar/feedback_pipeline
        ports:
        - containerPort: 8085
