apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback_pipeline
  labels:
    app: feedback_pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feedback_pipeline
  template:
    metadata:
      labels:
        app: feedback_pipeline
    spec:
      containers:
      - name: feedback_pipeline
        image: kartikjalgaonkar/feedback_pipeline
        ports:
        - containerPort: 8085
